### ISSUE TITLE
Disappearing stumps

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#363]
### What happened?

Sometimes when cutting a tree, the cut trunk will spawn in but not the stump. Maybe it's not set up right on certain tree types?

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Cut lots of trees until you see it

**Comment by westonleavitt** [comment]
I think we should consider adjusting the logic on the trees to not instantiate a new prefab but to instead operate from a single prefab. When breaking just disable the main harvestable and then activate child harvestable network behaviors. The more lag a server has the time between chopping and reinstantiating the new prefabs is going to increase

**Comment by westonleavitt** [comment]
These no longer function the same and should be fixed
