### ISSUE TITLE
Underwater Flashing lights

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/LostIsleBugTracker#397]
### Contact Details

Luke

### What happened?

Some funkiness happening with the underwater effects. See image.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

1. Go underwater

### Screen Recording or Screenshot

![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/100382919/22979d31-29f1-4403-8f84-7ffe38e47e60)

**Comment by westonleavitt** [comment]
duplicate of #543
