### ISSUE TITLE
health bars sometimes don't show the right value

### ISSUE THREAD

**Issue by nbaggett** [westonleavitt/LostIsleBugTracker#430]

**Comment by psyqotic** [comment]
![Screenshot 2023-11-28 113834](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/202c87eb-66d5-41b8-a5bf-4b3bba7bd312)
![Screenshot 2023-11-28 113846](https://github.com/westonleavitt/TheOccultBugTracker/assets/99694322/856a6b33-2be6-4de8-b707-efe9213c5764)

Values change before and after taking damage
