### ISSUE TITLE
If you look at a building part to show the amount of resources required UI, it'll show that UI for any interactable afterwards

### ISSUE THREAD

**Issue by nbaggett** [westonleavitt/LostIsleBugTracker#468]
![image](https://github.com/westonleavitt/TheOccultBugTracker/assets/43483627/b78b19dd-b243-47a0-962e-b014242d94a3)

**Comment by nbaggett** [comment]
0/200 stone still shows from when I was in upgrade mode.

**Comment by tykennington** [comment]
Tested going from upgrading to a countertop, and I couldn't recreate the issue. We've made a lot of fixes to AimCanvas since February, so it looks like this must've already gotten fixed at some point.
