### ISSUE TITLE
crafting should show a status tag when nearby

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#476]
no way of knowing when you are close enough to workbenches. lets add them as a status effect or something. Lets also add indicators inside of UI when you have crafting panel open, showing which benches are close enough

**Comment by tykennington** [comment]
Implemented the HUD status list in the bottom-right corner and another list next to the crafting menu.
Commits 132acd3da29e42bca754bc488f5bc208fb4a4877 and 25bc541ab59b72867f917ccec91d7821158a575b
