### ISSUE TITLE
When turning a machine on or off the rotation (ping pong it's called) resets to 0, jumping pretty crazily. I assume it happens on all machines, but here is the recycler: https://streamable.com/lt9fss

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#489]
When turning a machine on or off the rotation (ping pong it's called) resets to 0, jumping pretty crazily. I assume it happens on all machines, but here is the recycler: https://streamable.com/lt9fss

Activation on the ping pong effect just gets retriggered. this is an easy fix

**Comment by tykennington** [comment]
commit 7126904d81f9e2902c8839808ddb3dd29686e685
