### ISSUE TITLE
blood from harvesting bodies is really bright red. Almsot cartoonishly red.

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#493]
https://streamable.com/qq7c93 blood from harvesting bodies is really bright red. Almsot cartoonishly red.

**Comment by westonleavitt** [comment]
Fix:
Pause the game during a hit to find the material and tweak it. Make sure it looks good at day and night time.

**Comment by mckayrules** [comment]
Assuming I got the right particle systems, it's better. But I'm not sold on the ps in general. It's ok, just feels a little fake.
