### ISSUE TITLE
Held note hard to read

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#496]
### What happened?

The held note generally is held a bit low, which cuts off the bottom, but it gets especially bad during the fidget animations.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

1. Get a Blank Note
2. Right click the note and add some text to make a Written Note
3. Equip the Written Note

### Screen Recording or Screenshot

![Screenshot 2024-09-30 113358](https://github.com/user-attachments/assets/35048df5-89e9-41ae-8c0f-eef86743dbab)

**Comment by westonleavitt** [comment]
Trying setting up held item to parent to chest with dual hand ik
