### ISSUE TITLE
Door inventory icons too small

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#498]
### What happened?

Prison Door and Reinforced Iron Door are using icons that only fill a 4th of its space, making them very small compared to the wooden door icon

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Add Prison Door and Reinforced Iron Door to your inventory. Then look at your inventory.

### Screen Recording or Screenshot

![little_door](https://github.com/user-attachments/assets/e3a4a702-cad3-4829-9796-46ba72b7de94)

**Comment by westonleavitt** [comment]
Fix:
Just reexport the specific icons at a different resolution from the XD file.
