### ISSUE TITLE
Building preview raycast stuck on invisible triggers

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#500]
### What happened?

Building raycasts are currently set to collide with triggers, which gets janky when trying to build along their surfaces.
I'm not sure how much of an issue this is in the actual game where many of our triggers may be on excluded layers, but it came up in test scenes.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

1. Put a trigger collider in the scene.
2. Equip a deployable or the building hammer
3. Face the collider

### Screen Recording or Screenshot

![build_chair](https://github.com/user-attachments/assets/a56467b3-55a1-4bf3-aace-cd97209c341e)

**Comment by westonleavitt** [comment]
Fix: make sure building raycast only operates on terrain, socket, and building piece layer.

**Comment by nbaggett** [comment]
default is no longer a building raycast layer
