### ISSUE TITLE
Corpse costume issues

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#502]
### What happened?

Player corpses spawn in before the main player gameobject goes away, resulting in seeing two bodies next to each other at the same time until they respawn. Also, the player costume does not show on the corpse on clients.

That whole death sequence probably needs to be switched over to ragdoll like enemies/animals as well.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Die.

**Comment by westonleavitt** [comment]
@tykennington Can you review/fix this and close if complete

**Comment by tykennington** [comment]
Ragdolling was never set up (not sure if we're still going that direction or not), but the player costume and dna now correctly sync with both the corpse and the logged out body, and the player object is hidden when the corpse spawns in to make sure there is only one visible at a time.
