### ISSUE TITLE
Direct action-bar-to-storage transfer

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#506]
### What's your idea?

When storage is open, right clicking storage transfers and item to inventory, and right-clicking inventory transfers to storage. Right clicking action bar items, however, transfers them to the inventory as usual. Do we want it to go to storage instead?

**Comment by westonleavitt** [comment]
Yes.

**Comment by tykennington** [comment]
Fixed in commit 45064f8d0ca0a63244e1916b0d3c608dcd1ecabc 

I also did the same for armor slots, and added similar behavior on vendor screen
