### ISSUE TITLE
Stop airdrop payloads from being able to push them around

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#507]
### What's your idea?

Airdrops have rigidbodies as they fall from the sky. However, this means when they land they can still be pushed around. Maybe we should either increase the mass, or set it to kinematic when it touches the ground.

**Comment by westonleavitt** [comment]
Yes. Let's make their mass and drags high.

**Comment by tykennington** [comment]
commit 6c0e3637eed0872a1152e603cd4f9aa186d10ec4
