### ISSUE TITLE
Block building in doorway

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#512]
### What's your idea?

Other deployables are currently allowed to be built in the area when a door can swing open. The door will just pass through those object. It looks especially weird with wall deployables. Maybe we should block build in a door's path

### (Optional) Screen Recording or Screenshot

![Screenshot 2024-09-30 131945](https://github.com/user-attachments/assets/ffb5cf97-8f91-4f7f-9812-5d3445d785cf)

**Comment by nbaggett** [comment]
pretty sure ty said he fixed this so I'm going to close it
