### ISSUE TITLE
Destroy build option prompts/removal

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#514]
### What's your idea?

Currently while holding a building hammer, you can switch to destroy mode to quickly remove building parts with the R key. Was this mode supposed to be removed? If not, there's nothing in the UI currently that communicates that that's an option.

**Comment by westonleavitt** [comment]
Fix:
Disable the remove mode. This should not be accessible

**Comment by tykennington** [comment]
Looks like someone already beat me to it. It's disabled.
