### ISSUE TITLE
Stop wall deployables from hanging off so far

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#516]
### What's your idea?

Wall deployables (Wooden Wall Shelf and Wall Planter) currently only need their center to hit a wall surface, which means it can hang halfway off a corner. This looks odd with the wall mounts not actually on the wall. If we can, maybe we should adjust the build conditions to require the mount positions to be on a wall surface in addition to (or instead of) the center.

**Comment by westonleavitt** [comment]
Fix:
Can we maybe add some sort of required attachment points on the edges and only allow placement if all attachment points are also on a valid surface

**Comment by nbaggett** [comment]
added a field to the surface check condition with additional transforms to check from
