### ISSUE TITLE
Invisible harvestables

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#520]
### What happened?

Many, but not all, trees and rocks were invisible. They still let us collide with them and harvest them. And which showed and which were invisible was different on each client

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

We were testing the the Environment Playground 2 scene with a server and two clients.

**Comment by westonleavitt** [comment]
Should be fixed.
