### ISSUE TITLE
Status effect VFX on AI not centered on head after prefab changes

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#522]
### What happened?

Jake changed the Y position on the status effect VFX prefabs causing most of them to be floating 1.3 units in the air above the heads of AI. They just all need to be readjusted to be centered on the head of each AI

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Do something to an enemy UI that applies a debuff / negative status effect

**Comment by nbaggett** [comment]
reset all effects to local 0 for their transform. set attachment bone to choose where it is attached to or it can use root position. The offset amount can be used to choose how much it is offset from either the bone or the root
