### ISSUE TITLE
Move "Consumable expired!" message when food expires from chat window to alert message

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#525]
![Screenshot 2024-10-02 181831](https://github.com/user-attachments/assets/fb50db56-2a33-465e-8432-9e13ae95ff8f)

**Comment by psyqotic** [comment]
Also, make sure the message only happens once when a food expires. Seems to happen multiple times

**Comment by tykennington** [comment]
Fixed in commit 3b4cdf342fc55f124f18a7a1aad865a5f4f9a196
