### ISSUE TITLE
Mouse left click highlight stuck on "Place" after switching from building hammer to a weapon

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#526]
![Screenshot 2024-10-07 161943](https://github.com/user-attachments/assets/e6fad177-6ee1-497a-9e24-a59854e9b90a)
![Screenshot 2024-10-07 162000](https://github.com/user-attachments/assets/8559df52-ead1-4f52-a21f-d00e8a24e2e2)

**Comment by tykennington** [comment]
commit 11d41dbfb2bb00f29be3e576fdf23f17ead6423d
