### ISSUE TITLE
Triangle building pieces make pieces after it break when placing

### ISSUE THREAD

**Issue by tykennington** [westonleavitt/LostIsleBugTracker#527]
### What happened?

Triangle building pieces are breaking the build system. After building one, the next piece you place is stuck with the build preview overlapping the actual part, and you're unable to place any more parts after that.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

1. Build a triangle foundation or a triangle floor
2. Try building anything else

### Screen Recording or Screenshot

![Screenshot 2024-10-08 094455](https://github.com/user-attachments/assets/fd9917cb-a876-4de4-9428-dd3a1fc8b58a)

**Comment by nbaggett** [comment]
fixed, I was wrong it was in fact not easy to track down haha
