### ISSUE TITLE
Arcane Powder has strange numbers and doesn't clear from side feed

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/LostIsleBugTracker#532]
### What happened?

I picked up 6 arcane powder (maybe over multiple individuals instead of one at 6, idk) and on the side feed of items it says -230 arcane powder. 

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

??? No idea. Happened when I was collecting loot from broken barrels.

### Screen Recording or Screenshot

![image](https://github.com/user-attachments/assets/fefbe0cc-4bf9-405a-9aae-aab70de239c4)

**Comment by psyqotic** [comment]
I experienced the arcane powder sticking in my item feed even when adding other items from the console to my inventory
![Screenshot 2024-10-04 145701](https://github.com/user-attachments/assets/a905bb04-7d34-441e-abc0-aa9a6f373b15)

**Comment by tykennington** [comment]
Arcane Powder -230 was just the default before the icon and number  get set, so it was failing before then, when generating the name when it doesn't even display the name. So I stopped it from calling the name generation from there, and I did some more error handling on the name generation, so this shouldn't happen any more. If we have similar issues in the future though, I changes the default to this to make it more obvious:

![item_textual_feedback](https://github.com/user-attachments/assets/ed2ec8e7-e612-427c-a5a2-cebed02f13e3)
