### ISSUE TITLE
Timer cool down or whatever for the center notifications is not enough

### ISSUE THREAD

**Issue by mckayrules** [westonleavitt/LostIsleBugTracker#534]
### Feedback

If you click on lots of items or the same one a lot of times you can fill up the entire screen. Should probably only go up to maybe a quarter of the way. Only one of the same message would probably help too. Just have it flash when a new one is made instead of adding a new one to the stack.

### (Optional) Screen Recording or Screenshot

![image](https://github.com/user-attachments/assets/7780e7b9-e905-4853-8b63-32c5b9704992)

**Comment by tykennington** [comment]
commit 35bba6756a54790ea79de53cad5a170ec9fdf5e6 stops there from being identical alerts at the same time, and will make the existing one flash instead. This should be enough to stop it from filling the screen.
