### ISSUE TITLE
Tooltips not displaying stats

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#538]
![Screenshot 2024-10-14 120441](https://github.com/user-attachments/assets/78677839-b776-41e8-8212-8335a356fc56)
![Screenshot 2024-10-14 115531](https://github.com/user-attachments/assets/ea6ea7c7-cde5-44ad-bfab-4cc71b246650)
![Screenshot 2024-10-14 115415](https://github.com/user-attachments/assets/5728ac5d-8dce-4066-8b3a-4dd3c39db914)

**Comment by tykennington** [comment]
Fixed in commit 0ee1fa2a8f0bba596e2a704556136d98b940818c
