### ISSUE TITLE
Tooltips for Eaten food show an additional tooltip for hunger behind them?

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#546]
![image](https://github.com/user-attachments/assets/45d3ff9f-1b80-434a-809d-824f7efab6e9)

**Comment by tykennington** [comment]
commit e54f3d3beed84c277a33a2cc4fb008260ec51b38 

Removed the text-only tooltips on food slots in favor of the InventoryToolTip
