### ISSUE TITLE
Status Effect Values

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#547]
When in alt view or when holding alt in outside of alt view, show these fields near the status effects:

![image](https://github.com/user-attachments/assets/93d8518f-a850-4cba-9ce7-87b5fcbedefc)

use these for the values:

![image](https://github.com/user-attachments/assets/af518ef8-30e3-4f7c-aff4-69ee2f6a6f1a)

when outside of alt view show just the percentages (unless alt is held, then show percentages and value)

![image](https://github.com/user-attachments/assets/dd07df6a-b456-4c18-987c-69136025ee8c)

**Comment by tykennington** [comment]
Looks like sanity was removed from that part of the HUD, so there's no number display for that, but hunger and hydration values work now

commit 57c646ca0d9ca86f3372011abfc0c25590dea6bc
