### ISSUE TITLE
Tooltip Edge Cases

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#548]
1. In Crafting Panel (Note has line above the crafting section)
![image](https://github.com/user-attachments/assets/ea7d8300-e5fd-4f15-ad5a-1e189e34b71e)

2. Special Stats Vertical Alignment:
![image](https://github.com/user-attachments/assets/516f87de-fd7c-420d-88a1-e82bb8b075fe)

3. Special Stats Horizontal Alignment:
![image](https://github.com/user-attachments/assets/53ae8e9e-91b9-45bc-ad05-959657ccd95f)

4. Veritcal Alignment on Hero Icons (lets check them all, make sure even if the export is we self adjust so they look good):
![image](https://github.com/user-attachments/assets/a80e6f4e-e10e-4dca-9439-398cfec6012c)

5. Currently tooltip is too skinny so the longer hero titles have to be shrunk. move width to be more in realm of this:
![image](https://github.com/user-attachments/assets/5a36c565-1747-4420-afa3-20e6a2cffd94)

6. Reduce the text overlay in darkness a bit and make it function better for different text sizing, sometimes currently it misses:
![image](https://github.com/user-attachments/assets/6791b9f1-36de-4539-9d4f-6c019942a1a0)

7. red color on unable to craft is a little agressive (use this hex instead #C85A41):
![image](https://github.com/user-attachments/assets/d1aeccd7-89c6-4bc2-8870-7a5dd4a0e7f7)

8. make the craftable section use the same background setup as the special effect / use wells instead of using a custom panel:
![image](https://github.com/user-attachments/assets/eddc62a0-9c18-4238-859b-745c636bc3aa)

9. Bonus health and stats on food should show up in a custom use (make it programatic so that it reads the bonuses from the bonus stats (currently you have to hold alt to see them in grey):
![image](https://github.com/user-attachments/assets/4400cff4-6b8b-45e7-8750-b230446e7aec)

10. the special use, craft BG, etc that use the well effect should all use a color like this:
![image](https://github.com/user-attachments/assets/423967b2-6fb9-4ae5-88c8-680d315eec07)
currently they all just have variations of black it looks like:
![image](https://github.com/user-attachments/assets/a806ca9a-5595-471e-bd45-47d392442a4e)

11. Description doesn't align vertically perfectly with the lines:
![image](https://github.com/user-attachments/assets/69fe55ec-e5df-4a18-a9db-aa7cead24a27)

12. Custom Use doesn't align perfectly:
![image](https://github.com/user-attachments/assets/d6053a68-9a3c-428b-90c6-0c8b4e54b4cc)

13. Sizing, colors, alignments, in general and colors is still just a touch off. lets take another pass through and really try to clone the mockup. It may be a good idea to rebake the TMPro atlasses at a high resolution to ensure we have super crisp text.

![image](https://github.com/user-attachments/assets/325f8d39-95aa-4828-ad91-114f329d58c2)
![image](https://github.com/user-attachments/assets/7851192a-f83d-40f5-b83d-c26183669a96)

Here are the only fonts that should be enforced/used/rebaked:
![image](https://github.com/user-attachments/assets/36c1d16e-fc82-4bda-ab9b-fac12cd07282)

14. can you ping me when done. I want to do a little bit of cleanup on the font color/styling as well

**Comment by tykennington** [comment]
Complete. Although I'm thinking it might be a good idea to scale the entire tooltip up a bit to be sure everything is readable on small screens
