### ISSUE TITLE
Status Effect Finalization Numbers

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#549]
**Hydration:**
Max hydration should be 128 oz. It should take 120 Minutes for dehydration to drop from 128 to zero. If running ticks should cost 2x the hydration. Should start game at 50% hydration.

**Hunger:**
Max hunger should be 2,000 cal. It should take 90 minutes to go from 2000 cals to zero. if running, ticks should cost 2x the hunger. Should start game at 40% hunger

**Comment by tykennington** [comment]
commit 09602b5ed2387643ac7c2739fb28d7805f597b38

In the future, we can adjust these numbers on a scriptable object:
Assets\-Wunder\ScriptableData\HungerAandHydrationSettings.asset
