### ISSUE TITLE
The stylist is a flasher / check all the other clothes too.

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#553]
The final spawn for the NPC has this occuring. probably just something funky with the collider / cloth combo

![image](https://github.com/user-attachments/assets/fc5b4bf0-d9c4-4a07-b701-26a47a1ca1f3)

Fix for the stylist. probably need to check the settings for the cook too. I think she wears a dress

**Comment by jkhan007** [comment]
Pushed The prefabs with updated cloth constraints.
