### ISSUE TITLE
Add feedback in research panel when clicking on paths that you cant access

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#554]
When clicking on a tab without the resources to unlock do a center alert that says
![image](https://github.com/user-attachments/assets/cc55ca27-ddac-4ba9-800f-27d4baea1146)
**You dont have enough motes**

when clicking on a locked tab, do a center alert that says 

**Item not researchable yet**

**Comment by jkhan007** [comment]
![image](https://github.com/user-attachments/assets/9d5d3334-786b-403a-8df3-6dcdcdfca1cf)
