### ISSUE TITLE
Research additional help tooltips

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#555]
For research panel setup each of the following areas with hoverable tooltips similar to hunger that say the following:

![image](https://github.com/user-attachments/assets/b31c217f-5944-42bf-8758-878b3114fcbd)

**Tier 0 - Primitive**
Primitive recipes require no crafting station

**Tier 1 - Basic**
Requires a respective Tier 1 crafting station

**Tier 2 - Journeyman**
Requires a respective Tier 2 crafting station

**Tier 3 - Master**
requires a respective Tier 3 crafting station

**Comment by jkhan007** [comment]
![image](https://github.com/user-attachments/assets/d862ec4c-6c20-47cb-8b20-a658a493c3be)

Pushed the prefab with all the tool tips Added
