### ISSUE TITLE
Death corpse needs adjusted to use the omni rig isntead of the old multi-mesh body setup

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#557]
Currently the old setup use a broken apart prefab of the old megarig.
![image](https://github.com/user-attachments/assets/3cb81380-6074-45b9-88d5-17aa77d18762)

Everything works appropriately but we need to adjust it to use the omnirig prefab located here to get the visuals to function right:
![image](https://github.com/user-attachments/assets/3649c3ae-867b-43c1-a76a-1f2f4db37e83)

then on death/spawn make sure model type is set to multiplayer and both assigncustomlayer and assigncustomlightlayer are off:
![image](https://github.com/user-attachments/assets/3fa7b73d-9ed4-4925-ba41-37f6cc454912)

then update the costume using this method:
![image](https://github.com/user-attachments/assets/658ed653-54c4-4503-8efe-5cd8b5e68e44)

you may need to setup some custom methods to grab the proper DNA, it currently just grabs the DNA from here:
![image](https://github.com/user-attachments/assets/7d2973be-ac3c-4501-8af1-e686ef1d85e2)

**Comment by tykennington** [comment]
fixed
