### ISSUE TITLE
Set Loot Timers

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#558]
Set this loot timer functionality:
![image](https://github.com/user-attachments/assets/f4be308d-91a0-4808-8663-a52ee98cfd0a)

to 1s on lootable body, and All Crates (rare, medical, treasure, etc), the field is located on "StorageChest" and called "UnmovingTime"

![image](https://github.com/user-attachments/assets/05ae95ef-7d27-4565-910e-d7d0ca49e5a4)

**Comment by jkhan007** [comment]
![image](https://github.com/user-attachments/assets/7b373e8d-b14f-4b08-9108-203295737684)


Pushed These prefabs
