### ISSUE TITLE
Exit Menu Polish

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#559]
the following is all polish for when clicking exit in the main menu

1. Hide this during exit condition using its statebasedui component:
![image](https://github.com/user-attachments/assets/9ade5714-a9ab-4a42-b12d-46c48dc3c947)

2. hide this during exit condition using its statebasedui component (on 1. ArmorGroup):
![image](https://github.com/user-attachments/assets/8e19d763-1498-49c3-b857-8ec36edfbcf3)

There is a new exit menu design located here in the ui controller:
![image](https://github.com/user-attachments/assets/a6a08a4f-6d28-4da9-a9a3-53f02ba79c79)
![image](https://github.com/user-attachments/assets/7b394b13-72e7-40ee-802e-fefe32f29170)

make sure it functions with hover states, and make the buttons do what they did previously.

3. Exit to main menu should call the previous function
4. Exit to desktop should exit the application (called as previously setup)
5. calling "Cancel" should remove the exit condition from the state based ui
6. Delete the old canvas item

7. currently there is a bug when you click exit it doesnt disable the current top bar choice:
![image](https://github.com/user-attachments/assets/5f12ba99-f58a-4e23-8f88-9b2ab0c4cd98)
![image](https://github.com/user-attachments/assets/cf0722c8-c2ad-4d85-8e44-fafac61b16af)

adjust this so that when you click exit, it enters the exit mode and disables the other top mode choices

**Comment by jkhan007** [comment]
![image](https://github.com/user-attachments/assets/e29f9056-4dc0-4386-ad1f-d77965f14e34)
