### ISSUE TITLE
NPC Default Action

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#561]
Make buy and sell be the default action for NPCs, NOT talk:
![image](https://github.com/user-attachments/assets/1d3a240d-c0b6-466d-953a-f141ecb706b9)

this should show on the tooltip and run functionally as:

Jack Black
[F] Buy/Sell [F Hold] More Options

**Comment by tykennington** [comment]
commit 9d01204ad9639fe2ec91257ed65434b1a4c54da6
