### ISSUE TITLE
Hunger/Thirst not reset on death/respawn

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#562]
After dying, hunger and thirst dont seem to get reset. I just start dying again immediately.

![image](https://github.com/user-attachments/assets/1a496b97-0f80-490b-8098-d9eee2649dc2)

upon Death, Initial Respawn, or manual re-respawn, hunger and hydration should be to set to their default levels

**Comment by tykennington** [comment]
commit 0ad9052d68c632bdfc4653ba7f1932baa8cc4545
