### ISSUE TITLE
When focusing the search show visual indicators that you are inside of it and typing

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#566]
Currently focusing the search shows nothing:
![image](https://github.com/user-attachments/assets/b47b7790-d381-4afe-926a-ee78ce915a0f)

isntead show a blinking line like other typing input boxes:
![image](https://github.com/user-attachments/assets/f1c3f33f-cbca-4bcc-b96a-0dbb1085c132)

**Comment by jkhan007** [comment]
![image](https://github.com/user-attachments/assets/c86b3d74-9c3b-412e-9190-b1c66c27aac4)
Search cursor indicator  is working on my side
