### ISSUE TITLE
Health/stamina stats mismatched after consuming food

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#571]
Food seems to be buffing stamina and health, but the numbers also don't match. My health bar matches my stamina, and my max health has a different value. I don't have anything equipped so the food buffs should be the only things altering my stats here.
![image](https://github.com/user-attachments/assets/a412affb-ea80-4992-b20c-406efed6002d)

**Comment by tykennington** [comment]
fixed
