### ISSUE TITLE
Oxygen depletion not triggering immediately, status effect needs modified

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#572]
1. When you enter a water volume nothing happens for a few seconds, then eventually the Oxygen status appears in the bottom left but it depletes very quickly. It should start depleting gradually from the first second your head goes under the surface of the water.

https://streamable.com/0vkioz

2. Currently when Oxygen reaches 0 the bottom left status effect disappears. Instead, it should remain but change to "Suffocating" and remain there until the player dies or change back to Oxygen when the player leaves the water volume.

**Comment by tykennington** [comment]
commit d4167b578e338bc21b889865418b6c7fe1c71d54
