### ISSUE TITLE
NPCs spawning in/out with tiered machines

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#576]
https://streamable.com/6g0wfw
There's a lot going on here... but NPCs should not spawn with deployable machines. A random tooltip also appears and sticks on the screen. Should be able to recreate easily by equipping/placing/picking up an anvil

**Comment by tykennington** [comment]
fixed in commit ba089496aa9e5cb7786cbfc572657a77ce84eaf3.
