### ISSUE TITLE
Research tree and crafting tooltips should display base stats

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#577]
![Screenshot 2024-11-05 134804](https://github.com/user-attachments/assets/31b5d793-0424-4d03-8b96-e77cc7200716)
It looks like when previously removing rollable stats from research/crafting tooltips that the base stats also got removed. Stats that should be displayed on research/crafting tooltips should be:

-Physical Damage
-Magic Damage
-Armor
-Magic Resistance
-Insanity Resistance

**Comment by tykennington** [comment]
commit 98d293fd538c3cfb9e998901a65ab9b872f68a14
