### ISSUE TITLE
Additional tooltips

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#579]
1. Add a tooltip to the Motes tracker inside the research trees
![Screenshot 2024-11-05 133959](https://github.com/user-attachments/assets/df2f0430-6d2f-4292-8eed-bfbd5ae02a52)
It can match the other Motes tooltip near your action bar
![Screenshot 2024-11-05 133952](https://github.com/user-attachments/assets/6a053549-0696-46cf-94ca-fc343ce0c86a)

2. Add tooltips for each of the icons that appear when you're in range of a crafting machine
![Screenshot 2024-11-06 115317](https://github.com/user-attachments/assets/e2447f12-a25a-442e-978a-a13fd2009795)
These should have a header that says the name of the machine (Workbench, Anvil, Spinning Wheel, Reliquary), and text that reads "You are close enough for crafting and research."

**Comment by jkhan007** [comment]
Fixed
