### ISSUE TITLE
All machine status effect icons are 1 tier too high

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#581]
All of these machines are the base tier (1) but are displaying as tier 2
![Screenshot 2024-11-06 115317](https://github.com/user-attachments/assets/d6048e52-c084-4e6a-b44b-64946ac91951)
The maximum tier level should be 3, but it goes up to 4
![Screenshot 2024-11-05 143621](https://github.com/user-attachments/assets/bedf5b64-5a89-4bab-b95c-4cd6829fc5e3)

**Comment by tykennington** [comment]
commit ba089496aa9e5cb7786cbfc572657a77ce84eaf3
