### ISSUE TITLE
Machine tier 1 stays red after upgrading to and past that tier

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#582]
![Screenshot 2024-11-05 144102](https://github.com/user-attachments/assets/a0d9fa41-e7ff-4105-a53c-54ec75483fdf)
This should turn green after reaching or passing tier 1

**Comment by jkhan007** [comment]
![image](https://github.com/user-attachments/assets/2d82ce44-4173-43e5-bb1c-21461ccf1fb7)
