### ISSUE TITLE
Minor Text Adjustments on statuses

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#586]
Adjust the default hud text to have the numbers located here:

![image](https://github.com/user-attachments/assets/1105b95c-432d-485c-8282-781d425baa4d)

 add a small darkening behind the text to make it a touch more legible:
 
![image](https://github.com/user-attachments/assets/e587931e-0b53-41bc-a970-8d92d8e70716)

**WHEN IN ALT VIEW** lets adjust the designs to bump up in size slightly and be viewed like so:
![image](https://github.com/user-attachments/assets/52e6eb5e-9774-4daf-9f56-595ae9374760)

**Comment by tykennington** [comment]
commit 7ad87393ec4e4a3f1544d675562ceb2934513972
