### ISSUE TITLE
Consuming common foods no longer a status effect

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#587]
Common foods will just be for calorie maintenance and won't give any additional temporary bonus stats, so we need to remove their ability to become a status effect. If the "Base Consumable Duration" field has a value of 0 on their scriptable object, they should not appear as a status effect but should just be an instant calorie/hydration replenish
![image](https://github.com/user-attachments/assets/194a2541-c6e3-4651-9e97-03f6fb1670a4)

**Comment by tykennington** [comment]
Fixed in commits dddfb7629369a9b609b5843d24732d0eae617a70 and 2415ca7a2d8d9e5ecc8e25580e43dc0651738fbc

If duration is 0, the following immediate effects still apply when consumed:

- Calories
- Hydration
- Sanity add
- Health restore
- Consumable drop items (e.g. seeds)
