### ISSUE TITLE
Dig pile polish

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#589]
https://streamable.com/gg9cz7
Here's what interacting with a relic pile currently looks like (ignore the actual loot - it needs work). This system needs some polish and unique functionality to make it feel better.

1. Bug: items are not showing up in the item feed on the bottom right
2. New Functionality: new container type that requires channeling but doesn't take you to an inventory at the end. Make it skip the part where it opens the "container". The items should just automatically be added to your inventory and the dirt pile should destroy/despawn.
3. Polish: play particle effect(s) during channel like dust and small stone particles. We will have a player-digging animation eventually to go together with this

**Comment by psyqotic** [comment]
You can use this scene to test dig piles - they're fully set up
![image](https://github.com/user-attachments/assets/6a096e11-708a-4e91-822e-65755fa3a79e)

**Comment by tykennington** [comment]
commits dcb4752 and 7e20221
