### ISSUE TITLE
Remove Item Stars

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#590]
![image](https://github.com/user-attachments/assets/92ee50af-2518-4c13-bc47-9df92a12035e)
We want to remove the sprites that show up indicating the item rarity on green and blue items.  Can you adjust them to just be disabled. we might rework the functionality in the future

**Comment by jkhan007** [comment]
Fixed and pushed the code
 ItemIcon Prefab & (Quality Icon) Disabled
