### ISSUE TITLE
Tab menu requires clicking something before exiting

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#591]
If you push Tab to open the alt menu and push Tab again to try to close it nothing happens. You have to click something first, then you can push Tab to close the menu. Pushing Tab at any time should close it.

**Comment by jkhan007** [comment]
Fixed and pushed. 

UIController-> InventoryOpenKeyPressed (method) -> NoMoveMenuopen check commented

![image](https://github.com/user-attachments/assets/42b7ee32-b9be-449d-878a-201b30d9aafc)
