### ISSUE TITLE
Add tooltips to map marking icons and legend

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#592]
![Screenshot 2024-11-11 174310](https://github.com/user-attachments/assets/d5fc13a9-81bc-486c-b873-db0dd8d7003b)
When you open the map none of these icons have tooltips. All three of these places need them - on the left, when you drag them from the left on to the map, and the legend icons on the bottom. For now just add temporary filler descriptions and we'll get final descriptions soon.

**Comment by jkhan007** [comment]
Fixed and pushed the code. here is the demo video as well
https://streamable.com/p43j92
