### ISSUE TITLE
Two corpses when dying to suffocation

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#594]
![Screenshot 2024-11-12 091703](https://github.com/user-attachments/assets/20e6791e-fb3c-4b41-8eed-e3cf7a3e9d5a)
This doesn't seem to happen when I die to other sources like to AI or falling, but when suffocating two corpses appear on the death screen.

**Comment by tykennington** [comment]
commit 2333ed4 hides the player object as the corpse spawns in, and then re-shows it after it's moved to the respawn point, so that there is only one visible body at a time.
