### ISSUE TITLE
Only show most recent corpse marker on map

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#598]
Currently if you die multiple times in a relatively short window it will show multiple corpse markers on the map. Change this to only show the latest death's corpse marker.
![Screenshot 2024-11-11 174013](https://github.com/user-attachments/assets/5dd36794-b830-4658-9af8-0f06875baf5e)

**Comment by tykennington** [comment]
commit 1ca7620088097def4cec0ef026f089bc90a7619c
