### ISSUE TITLE
HP depletion actual vs delayed values

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#600]
When taking frequent ticking damage (like from suffocating) the delayed HP value gets too far behind the actual HP value. In this case, with suffocating, when I died the delayed health meter was still nearly at 50%. I'm not sure what exactly the fix is, but the delayed pace shouldn't be so far behind in cases like this. Let's sync up when you start on this one.
![Screenshot 2024-11-11 171435](https://github.com/user-attachments/assets/7c31b0be-1636-4902-a902-47f05101dfa5)

**Comment by tykennington** [comment]
commit 11ddd4f9e9351fd71e5fe04c7c2e801ac2ca3a6b
