### ISSUE TITLE
Create new unique harvestable for Forest Golem's rock throw

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#603]
The golem still spawns in and throws a rock, but once it's thrown it doesn't become harvestable or break into pieces
![Screenshot 2024-11-13 140243](https://github.com/user-attachments/assets/b02979f2-0c56-4019-9fa4-9e074bafe894)
Need to setup a unique harvestable for them instead of using the open world rock. The harvestable rocks/trees are not allowed to move because they use a special type of instancing and batching setup that allows them to be performant at the cost of not moving.

The rock also needs to have high mass and drag. It's currently super easy to push/roll around

**Comment by nbaggett** [comment]
Added these as new harvestable fragments that spawn when the boulder collides with a surface
