### ISSUE TITLE
Crafting tab highlighted by default

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#612]
If you push the M hotkey to open the world map, the Crafting tab is highlighted by default at the same time the World Map tab is highlighted. Only one should be highlighted at once. Change this so that when you push M to open the world map it's the only tab highlighted.
![Screenshot 2024-11-14 160536](https://github.com/user-attachments/assets/55050566-3445-4e4c-819f-d77b96e276c8)

**Comment by jkhan007** [comment]
![Uploading image.png…]()
