### ISSUE TITLE
Build Definition Issues

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#614]
There are instances currently of unescaped editor code usage inside player codebase and inappropriate includes. You can find out where by attempting to rebuild the addressables.

 **Window > Asset Management > Addressables > Groups**
 
 then from that panel click Build > New Build > Default Build Script:

![image](https://github.com/user-attachments/assets/9f73002b-434b-4d3b-b899-16d6540289fe)

this will run a forced compilation that will error if any editor code is detected. for example here:
![image](https://github.com/user-attachments/assets/85002124-b80a-407c-a465-867fb769fde8)

we then need to trace those errors and fix the editor name space or issue referenced.

i.e. the error here was use of assetdatabase inside non editor script:
![image](https://github.com/user-attachments/assets/e73c506c-ad8b-460f-a26a-e975677c7822)

fix is just to escape that functionality:
![image](https://github.com/user-attachments/assets/0b86fd7b-32ac-41ca-9666-4d525b4a75b6)

run the addressables test cycle until it completes fully and there are no errors left.

**Comment by tykennington** [comment]
commit b5a2bd8
