### ISSUE TITLE
Furnace UI overlapping

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#616]
1. An inventory UI is overlaying the furnace machine UI
![image](https://github.com/user-attachments/assets/71e7b92e-8174-4d5f-842d-b9ad56321ebb)
2. Smoke particle system is black boxes

**Comment by psyqotic** [comment]
Same with Supply Barrel
![image](https://github.com/user-attachments/assets/07e0441e-b5cf-418b-8bb9-b502f581f1aa)

**Comment by tykennington** [comment]
No longer able to reproduce.
I had encountered the weird smoke in the UniversalTestScene at one point, but it no longer happens there, or anywhere else I've tested.
