### ISSUE TITLE
Upgraded deployables revert to tier 1 after moving

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#621]
https://streamable.com/djmlp6
Make sure the current tier and upgrade progress saves when you pick up and move them.

**Comment by tykennington** [comment]
Workbench xp/tier now persists with commit d6a473a

However, there's not currently anything in the UI indicating this. It's the same icon in the inventory, and the tooltip says nothing about xp. How do we want that communicated/displayed?

**Comment by tykennington** [comment]
Also should probably show the upgraded version in the build placer preview, but these are just polish items that we can open later as their own issues, and I'll close this one.
