### ISSUE TITLE
Health values not mathing

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#622]
![Screenshot 2024-11-18 131419](https://github.com/user-attachments/assets/33c56a64-df1b-417f-b2e8-9f2e5f9e2813)
I only have one health modifier coming from a food buff (+15), and some stat points assigned to health (+6), so my health stat value is accurate at 121, but my health bar is saying 154. The only thing I can think of is that I consumed other food earlier that gave additional health buffs, so maybe the buff didn't expire when the food did?

**Comment by tykennington** [comment]
commit 18f8dbe
