### ISSUE TITLE
World map should not show trees/foliage. Easy fix in descriptions

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#623]
Just add this component to the ortho map cam:

![image](https://github.com/user-attachments/assets/7e4dff17-4b34-49bc-82bd-415f007559ec)

and make sure render is OFF

this will prevent the tree rendering effect:
![image](https://github.com/user-attachments/assets/d01ce35a-d488-4608-b37b-dfc48d54c4b8)

![image](https://github.com/user-attachments/assets/f4ec1eee-a7b1-4694-a10a-667aa26649fb)

**Comment by tykennington** [comment]
commit 32963d6
