### ISSUE TITLE
Allow map axis movement to operate indepedently and at the same time

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#624]
currently the map can only drag up/down or left/right per click. make it so you can do them both at the same time and independently. 

![image](https://github.com/user-attachments/assets/fcd31047-d02d-4d76-930b-e08e0c47ff6c)

**Comment by tykennington** [comment]
I haven't been able to recreate this (tested in EnvironmentPlayground2 scene), unless I'm misunderstanding the issue. The map seems to be freely draggable diagonally/in any direction, without locking to an axis.

**Comment by tykennington** [comment]
Cannot recreate
