### ISSUE TITLE
Map Padding

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#625]
Allow the map to drag significantly more. (We will make sure to fill extra water on the sides in the build scenes with the map material)

currently the maxes are the edge of the terrain like so:
![image](https://github.com/user-attachments/assets/bfcad603-12a4-4910-b49a-8d72b7681230)

lets allow it to move something more like these:
![image](https://github.com/user-attachments/assets/aa0a753e-9dd8-4bda-b24e-4784922f1c73)

**Comment by tykennington** [comment]
I added a padding field to the map script if we ever need to make adjustments.
commit c978c4b
