### ISSUE TITLE
Currently crafting status bar shows the stamina icon. it should show a rotating cog of the same color

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#631]
![image](https://github.com/user-attachments/assets/3b9440c8-d4e0-423f-ba48-652d89f99a49)

just swap to use the cog and add the rotator script

![image](https://github.com/user-attachments/assets/220e9d8f-d267-4d70-8ce8-3d04f389877f)

**Comment by tykennington** [comment]
commit fc00c8d
