### ISSUE TITLE
Crafting queue shows a large list of progress bars if queue is long

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#632]
Currently crafting shows 1 progress bar for each item in crafting queue. Lets move this to just be a single bar that only shows the CURRENT crafting item. even if there is queue. then when the queue updates, adjust it to be the new item.
![image](https://github.com/user-attachments/assets/ad9c9cc3-6a78-495f-a944-d08615f99a74)

**Comment by tykennington** [comment]
commit dade821
