### ISSUE TITLE
Target dependent focus building

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#639]
Currently combat specialized weapons (like a two hand battle axe) can build focus by hitting harvestables. Need to figure out some kind of detection so this isn't the case or players will just pre-charge focus on a tree before attacking a player. It's not really a big deal the other way around (harvest specialized tools building focus by hitting players or AI). Reach out when you're ready to tackle this and we can discuss it further.

**Comment by nbaggett** [comment]
now adds focus based on harvest effectiveness, so since other non harvesting tools can get resources the amount of focus added is significantly reduced
