### ISSUE TITLE
Wall planter doesn't display water duration

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#640]
![Screenshot 2024-11-20 173821](https://github.com/user-attachments/assets/f9c15474-9298-400b-adb5-ee831fc626e2)
![Screenshot 2024-11-20 173829](https://github.com/user-attachments/assets/e91e9bde-6524-4ad3-b5fe-a92b3d19e40d)
![Screenshot 2024-11-20 173849](https://github.com/user-attachments/assets/5d2494cb-fc11-454a-9914-c37d0e9c5f0d)
The wall planter has a different aimcanvas display than the garden pot/planter and doesn't show water duration (I double/triple checked that I watered it, haha)

**Comment by tykennington** [comment]
commit 9c48971
