### ISSUE TITLE
Air ship missing reference exception error

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#644]
![Screenshot 2024-11-22 134037](https://github.com/user-attachments/assets/94ea441e-d367-4914-a538-0da3f892bc06)
Tested all of the signal torches and a chest only dropped with the green signal torch. Blue, orange, purple and red all summoned the air ship, but when it passed overhead it didn't drop a chest. Got this error each time. Look into what's causing this error and why chests aren't dropping when the non-green torches are placed.

The container that the air ship successfully dropped with the green signal torch was empty (no loot inside), but that is most likely a loot table assignment issue.

**Comment by tykennington** [comment]
McKay's commit 10b2da4 seems to fix this
