### ISSUE TITLE
Overlapping inventory UIs is back

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#657]
The overlapping UI issue is back. 
![Screenshot 2024-11-26 112647](https://github.com/user-attachments/assets/328ee978-d49d-4e61-9b55-634b7ae67d1a)
![Screenshot 2024-11-26 112655](https://github.com/user-attachments/assets/1e6f8579-eb36-4787-9b74-28278d834c09)
These are the deployables I currently have. Not sure what is causing it, but maybe you can get it to happen on your end by replicating my setup
![Screenshot 2024-11-26 112742](https://github.com/user-attachments/assets/5116991f-0fa8-4afd-9eb4-3805811f28b2)

**Comment by tykennington** [comment]
I added a failsafe in commit 601337b
If for whatever reason a storage panel does not close properly, it will go and close it when you try opening a different one
