### ISSUE TITLE
Have searching use the search cursor

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#662]
when hovering search in crafting:

![image](https://github.com/user-attachments/assets/986dae51-37ed-43cd-91c8-ede5b5378f35)

use the search cursor:

![image](https://github.com/user-attachments/assets/bc3ee07b-e640-4361-bb74-e69c9f770ac1)

**Comment by tykennington** [comment]
commit b33f11c
