### ISSUE TITLE
Relic turn-in at reliquary not functioning

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#664]
It worked at one point, but doesn't seem to be working now. Look into the reliquary system and make sure that you can take any relic and "give" it to the reliquary. It should activate the active state with animations/particles, consume your relic, and give you 50 motes.

**Comment by tykennington** [comment]
Now working from an option in the circle menu; Dragging items onto it from the inventory is still disabled though
