### ISSUE TITLE
Deed of Ownership Configuration Polish

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#668]
I've update the deed of ownership to only have 4 name slots. Make sure the name slots use one of the following configurations depending on how many players are on the deed:

![image](https://github.com/user-attachments/assets/448b8704-e6e6-4960-a504-f485c8b5584a)

**0. Setup the property deed deployable to use the new psd sprite**
![image](https://github.com/user-attachments/assets/7aefadd2-a59e-4c86-8a60-df5e5846cf65)

**1. under owership report show the player names properly**
a. 0-4 players, just show each player per line or 
b. more than 4 players, show the first 3 players and on the fourth line show +n others

**2. Settlement Report**
On the second half of the deed of ownership we want to show the settlement scores (the same scores we setup for deployable items). We need to calculate this based on the placed items within the deeds radius. We also need to do it very performantly (maybe every few seconds we ping a quadtree of all placed items and get stuff thats within the radius or something). These settlement scores will affect things in the future so we need to be able to access them. The settlement scores should update as players place items throughout their build privilege.

In each settlement report box should just be a text number between 0 and 99+ being the max

**3. Setup some basic stats on all deploaybles for +civilization score, +luxury score etc and ensure that all scores are functioning**

**4. Ensure that the tooltip properly shows these as if they are bonus stats for the deployable items**

**5. Add to tooltip text for deed of ownership that it provides settlement report**

**Comment by tykennington** [comment]
Complete.

There seems to be a problem with picking the deed up (It says you don't have build permission even when it's signed), but that's a different issue.

The stats probably need adjustment as well. I gave most deployables 2 of the 4 stats that I figured may be applicable, ranging from 1 to 5 points each.

**Comment by westonleavitt** [comment]
@tykennington  Reopening this for a few additional requirements:

1. If no owners are on the deed show "No Owners Assigned" on the top line
2. Implement the initial mechanics of the deed (you may need to sync with nick on some of the implementations):
     A. **Respawn Cooldown** - As luxury moves from 0-99, respawn cooldown of beds/bags inside the radius should go from 1x (10 minutes to .3x 3 minutes) (beds should go from 6 minutes to 1 minute) (this does not affect beds outside of radius)
     B. **Max Build Height** - As science goes from 0-99 max build height should go from 1 to 7. this should be the max floors from the foundation. probably need to calculate using height or something and should work in tandem with the stability
     C. **Machine Speed** - as industry goes from 0-99 machine speed should go from 1x to 4x. this should affect all generation and refinement machines (furnace, drying rack, etc)
     D. **Upkeep** - as culture score goes from 0-99 upkeep should go from 2x to .5x effectively reducing the cost of upkeep/decay over time
     
     
    3. Cap the decimals to 1 decimal point i.e. 3.1

**Comment by tykennington** [comment]
Fixed. Although it looks like the stability system goes off distance from the foundation, and gives full stability when the distance is 2 or less. So I adjusted it to be 2-7 instead, and it isn't *exactly* the build height, since it affects how far you can build outward as well as upward. But this seemed like the best way to fit it to our current systems.
