### ISSUE TITLE
Eating on Server / Client Fixes

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#679]
Currently you cant eat at all on server/client. it gives you a warning saying 3s food cooldown, even on first attempt.

HOWEVER -- Lets remove this adjustment entirely for food. Food should be spammable from actionbar AND from inventory. Consumables (not food consumables like potions, bandages, etc) should be the only thing that have the 3 second cooldown.

Those do need to have the cooldown and the cooldown should not prevent initial usage and should have a properly functioning cooldown tirme

**Comment by tykennington** [comment]
Potential fix push, but I was having trouble recreating the stuck-in-cooldown issue (tested with ParrelSync), so the fix needs verification. The cooldown was also removed from food and fixed for non-food consumables
