### ISSUE TITLE
Research on top of machines

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#689]
Machines can clearly be overlayed on top of researching through the following steps:

1. Open a machine by interacting with it (i.e. click f on a furnace)
2. from the top menu click research

![image](https://github.com/user-attachments/assets/4ae36958-30f5-4032-9f33-02e0d2a5459f)

Switching to any other tabs on the top bar should close the machine panels. This needs to function for all machines, lootables, etc.

**Comment by tykennington** [comment]
commit 52fc74f
