### ISSUE TITLE
Clicking close button in inventory UIs triggers an attack/use of equipped item

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#692]
When you have an inventory UI open and you click close, it triggers the use of whatever item you currently have equipped. This needs to be disabled. Make sure when you click to close that's the only thing that happens
https://streamable.com/tu3gx9

**Comment by tykennington** [comment]
commit 127042d

**Comment by psyqotic** [comment]
Apply the same fix to closing/exiting any type of container, including skeleton corpses.

**Comment by tykennington** [comment]
commit 2bcaedf should _actually_ fix it
(I disabled adding click inputs to the attack buffer while menus are open)
