### ISSUE TITLE
Reliquary deployable is facing backwards by default

### ISSUE THREAD

**Issue by psyqotic** [westonleavitt/LostIsleBugTracker#693]
Reliquary deployable is facing backwards by default when you place it - also doesn't have the proper preview shape (tier 1 has the tier 3 preview)

**Comment by tykennington** [comment]
![reliq_front](https://github.com/user-attachments/assets/5bc4308c-3d50-4121-965b-0dfdb24389d8)
Is the book not the front of the reliquary? This is how it's rotated by default for me (both in the build and in the editor). I thought it was backwards before, so I rotated it to make the book face the player as shown on Dec 3 (commit 01e7282)
