### ISSUE TITLE
Deployables, Building Pieces, etc should all use subsurface scattering to improve shadows/coloring

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#695]
subsurface scattering needs to be enabled on all our deployables and building pieces. See below the difference:

![image](https://github.com/user-attachments/assets/48db161a-9ebd-485d-8b6f-72766057dae2)

Go through the prefabs in these folders:

![image](https://github.com/user-attachments/assets/d23f3299-a698-4e95-ae32-8b94dbc7e844)

and ensure that their material types for the lit shaders use SSS. You can do this by following these steps:

1. find the object and material (i.e. here is a cart currently set to standard, notice the material settings and notice the very dark shadowing):
![image](https://github.com/user-attachments/assets/da5ee83e-31c4-4b3f-95bb-6756909f2dc0)

2. Change the material type to sub surface scattering (notice each of the field changes -- diffusion profile, thickness, surface mask, and material type, then notice the changes in the models shadows) :
![image](https://github.com/user-attachments/assets/a48f7409-d02e-4a3b-b952-40a99853a77a)

**Comment by jkhan007** [comment]
Pushed all the materials files.
