### ISSUE TITLE
Documentation/Cleanup for All Console Commands

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/LostIsleBugTracker#696]
We've added a table here in nuclino:

![image](https://github.com/user-attachments/assets/5be9e665-74ce-4766-8833-10eb9ad1a161)

https://app.nuclino.com/Wunder-Entertainment/Documentation/Console-Commands-96dafa6f-929e-490c-9507-1abf5a627191

Can you go through the game and make a list of all commands so that we can organize them into namespace and get proper descriptions. There are some we will want to add and some we want to remove but this will be our starting place

**Comment by jkhan007** [comment]
![image](https://github.com/user-attachments/assets/1c1fc1aa-e116-401e-a253-3586442f6de4)


updated document of all the server commands in Nuclino
